services:
  mysql:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      # MYSQL_DATABASE: 'belajar_golang_restful_api'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    volumes:
      - "belajar-golang-restful-api:/var/lib/mysql"
    networks:
      - belajar-golang-restful-api
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: "user"
      MYSQL_ROOT_PASSWORD: "root"
      PMA_HOST: mysql
      UPLOAD_LIMIT: 1000M
    networks:
      - belajar-golang-restful-api

networks:
  belajar-golang-restful-api :
    driver: bridge
volumes:
  belajar-golang-restful-api:
    name : belajar-golang-restful-api